#!/usr/bin/env python3
"""Regenerate fonts.css from SUBTITLE_FONTS in ../app.js (run from repo root or fonts/)."""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent
FONTS_SHARED_JS = ROOT.parent / "fonts-shared.js"
OUT_CSS = ROOT / "fonts.css"


def parse_subtitle_fonts(source: str) -> list[dict[str, str]]:
    match = re.search(r"const SUBTITLE_FONTS = \[([\s\S]*?)\n\s*\];", source)
    if not match:
        raise SystemExit("SUBTITLE_FONTS not found in fonts-shared.js")
    block = match.group(1)
    fonts = []
    for entry in re.finditer(
        r"\{\s*family:\s*'([^']+)',\s*regular:\s*'([^']+)',\s*bold:\s*'([^']+)',?\s*\}",
        block,
    ):
        fonts.append(
            {
                "family": entry.group(1),
                "regular": entry.group(2),
                "bold": entry.group(3),
            }
        )
    return fonts


def font_format(file_name: str) -> str:
    ext = Path(file_name).suffix.lower()
    if ext == ".otf":
        return "opentype"
    if ext == ".woff2":
        return "woff2"
    return "truetype"


def emit_css(fonts: list[dict[str, str]]) -> str:
    lines = [
        "/* Auto-generated by fonts/generate-fonts-css.py — do not edit by hand */",
        "",
    ]
    for font in fonts:
        family = font["family"]
        if font["regular"] == font["bold"]:
            fmt = font_format(font["regular"])
            lines.extend(
                [
                    "@font-face {",
                    f"  font-family: '{family}';",
                    f"  src: url('{font['regular']}') format('{fmt}');",
                    "  font-weight: 400 700;",
                    "  font-style: normal;",
                    "  font-display: swap;",
                    "}",
                    "",
                ]
            )
            continue
        for weight, key in [(400, "regular"), (700, "bold")]:
            file_name = font[key]
            fmt = font_format(file_name)
            lines.extend(
                [
                    "@font-face {",
                    f"  font-family: '{family}';",
                    f"  src: url('{file_name}') format('{fmt}');",
                    f"  font-weight: {weight};",
                    "  font-style: normal;",
                    "  font-display: swap;",
                    "}",
                    "",
                ]
            )
    return "\n".join(lines).rstrip() + "\n"


def main() -> None:
    source = FONTS_SHARED_JS.read_text(encoding="utf-8")
    fonts = parse_subtitle_fonts(source)
    OUT_CSS.write_text(emit_css(fonts), encoding="utf-8")
    print(f"Wrote {len(fonts)} families to {OUT_CSS}")


if __name__ == "__main__":
    main()
